[package]
name = "home-config"
version = "0.2.1"
edition = "2021"
description = "Use configuration file in the HOME directory"
homepage = "https://github.com/wyhaya/home-config"
repository = "https://github.com/wyhaya/home-config.git"
authors = ["wyhaya <wyhaya@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = [
    "config",
    "json",
    "home"
]

[dependencies]
dirs = "4.0.0"
serde = {version = "1.0.136", features = ["derive"]}
serde_json = "1.0.79"
