[package]
name = "home-config"
version = "0.3.0"
edition = "2021"
description = "Use configuration file in the HOME directory"
homepage = "https://github.com/wyhaya/home-config"
repository = "https://github.com/wyhaya/home-config.git"
authors = ["wyhaya <wyhaya@gmail.com>"]
license = "MIT"
readme = "README.md"
keywords = [
    "home",
    "config",
    "json",
    "yaml"
]

[package.metadata.docs.rs]
features = ["json", "yaml"]

[features]
default = []
json = ["serde", "serde_json"]
yaml = ["serde", "serde_yaml"]

[dependencies]
dirs = "4.0.0"
serde = { version = "1.0.137", features = ["derive"], optional = true }
serde_json = { version = "1.0.81", optional = true }
serde_yaml = { version = "0.8.24", optional = true }
